# This file has been generated by node2nix 1.1.1. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
  };
  # src = pkgs.fetchgit {
  #   url = http://git.zero.monster.cat/payments-server;
  #   rev = "9fa106bb1c637ceeb4fd7e7ad94ed7a41725bd2c";
  #   sha256 = "0ic6nh4xnwpj4vbyxgfgs3r84f7q9v36lzf84hf9kr1ca455mhjx";
  # };
  src = /home/jb55/projects/monstercat/payments-server;
in
(import ./node-packages.nix {
  inherit (pkgs) fetchurl fetchgit;
  inherit nodeEnv src;
}).package
