# This file has been generated by node2nix 1.1.1. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
  };
  src = pkgs.fetchgit {
    url = http://git.zero.monster.cat/payments-server;
    rev = "d4409a996f7c3c6c3e2d6ede0e0c97765ebfa106";
    sha256 = "0vhh2xd93y1xkb4kh2md3j3wn1h09v68acwriqimgc5vmhbxw2rv";
  };
in
(import ./node-packages.nix {
  inherit (pkgs) fetchurl fetchgit;
  inherit nodeEnv src;
}).package
