# This file has been generated by node2nix 1.1.1. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
  };
  src = pkgs.fetchgit {
    url = http://git.zero.monster.cat/payments-server;
    rev = "b665d6c4ec34de111e699eed34a05ebdb04615e4";
    sha256 = "07vhvqhqnp7xkaym09xd8k6hry5h5168xkjm32jxx2vdvgcam4vb";
  };
in
(import ./node-packages.nix {
  inherit (pkgs) fetchurl fetchgit;
  inherit nodeEnv src;
}).package
