# This file has been generated by node2nix 1.1.1. Do not edit!

{src, nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-2.1.4" = {
      name = "async";
      packageName = "async";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.1.4.tgz";
        sha1 = "2d2160c7788032e4dd6cbe2502f1f9a2c8f6cde4";
      };
    };
    "aws-sdk-2.7.10" = {
      name = "aws-sdk";
      packageName = "aws-sdk";
      version = "2.7.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.7.10.tgz";
        sha1 = "d914ca2bdb6ff8b48cdbc20d617b7c6b6031c138";
      };
    };
    "bcryptjs-2.3.0" = {
      name = "bcryptjs";
      packageName = "bcryptjs";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.3.0.tgz";
        sha1 = "5826900cfef7abaf3425c72e4d464de509b8c2ec";
      };
    };
    "connect-redis-3.1.0" = {
      name = "connect-redis";
      packageName = "connect-redis";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect-redis/-/connect-redis-3.1.0.tgz";
        sha1 = "25a3c0f20def3e462caa2583eefeb67ca6b10c09";
      };
    };
    "cors-2.8.1" = {
      name = "cors";
      packageName = "cors";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cors/-/cors-2.8.1.tgz";
        sha1 = "6181aa56abb45a2825be3304703747ae4e9d2383";
      };
    };
    "dot-lens-1.2.3" = {
      name = "dot-lens";
      packageName = "dot-lens";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-lens/-/dot-lens-1.2.3.tgz";
        sha1 = "473572c355885202711ab2af86fa9d21c89b45a7";
      };
    };
    "express-4.14.0" = {
      name = "express";
      packageName = "express";
      version = "4.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.14.0.tgz";
        sha1 = "c1ee3f42cdc891fb3dc650a8922d51ec847d0d66";
      };
    };
    "express-session-1.14.2" = {
      name = "express-session";
      packageName = "express-session";
      version = "1.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express-session/-/express-session-1.14.2.tgz";
        sha1 = "6bcf586ed6d1dc37b02570087756c9de7b80b275";
      };
    };
    "multer-1.2.0" = {
      name = "multer";
      packageName = "multer";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multer/-/multer-1.2.0.tgz";
        sha1 = "5be1a45259fb04d2753d33c7c2a1caf5224705a2";
      };
    };
    "pg-6.1.0" = {
      name = "pg";
      packageName = "pg";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg/-/pg-6.1.0.tgz";
        sha1 = "4ebc58100a79187b6b98fa5caf1675d669926b41";
      };
    };
    "randomstring-1.1.5" = {
      name = "randomstring";
      packageName = "randomstring";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomstring/-/randomstring-1.1.5.tgz";
        sha1 = "6df0628f75cbd5932930d9fe3ab4e956a18518c3";
      };
    };
    "redis-2.6.3" = {
      name = "redis";
      packageName = "redis";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-2.6.3.tgz";
        sha1 = "84305b92553c6a1f09c7c47c30b11ace7dbb7ad4";
      };
    };
    "s3-blob-store-1.2.3" = {
      name = "s3-blob-store";
      packageName = "s3-blob-store";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/s3-blob-store/-/s3-blob-store-1.2.3.tgz";
        sha1 = "2e6f26c772708d5dcfc0d13e61e429deaefc342a";
      };
    };
    "sendgrid-4.7.1" = {
      name = "sendgrid";
      packageName = "sendgrid";
      version = "4.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sendgrid/-/sendgrid-4.7.1.tgz";
        sha1 = "38a6f1798dcdbb46361767ae4f5271104dcd232f";
      };
    };
    "lodash-4.17.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.2.tgz";
        sha1 = "34a3055babe04ce42467b607d700072c7ff6bf42";
      };
    };
    "buffer-4.9.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "4.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-4.9.1.tgz";
        sha1 = "6d1bb601b07a4efced97094132093027c95bc298";
      };
    };
    "crypto-browserify-1.0.9" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-1.0.9.tgz";
        sha1 = "cc5449685dfb85eb11c9828acc7cb87ab5bbfcc0";
      };
    };
    "jmespath-0.15.0" = {
      name = "jmespath";
      packageName = "jmespath";
      version = "0.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jmespath/-/jmespath-0.15.0.tgz";
        sha1 = "a3f222a9aae9f966f5d27c796510e28091764217";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "sax-1.1.5" = {
      name = "sax";
      packageName = "sax";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.1.5.tgz";
        sha1 = "1da50a8d00cdecd59405659f5ff85349fe773743";
      };
    };
    "url-0.10.3" = {
      name = "url";
      packageName = "url";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.10.3.tgz";
        sha1 = "021e4d9c7705f21bbf37d03ceb58767402774c64";
      };
    };
    "uuid-3.0.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.0.0.tgz";
        sha1 = "6728fc0459c450d796a99c31837569bdf672d728";
      };
    };
    "xml2js-0.4.15" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.15.tgz";
        sha1 = "95cd03ff2dd144ec28bc6273bf2b2890c581ad0c";
      };
    };
    "xmlbuilder-2.6.2" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-2.6.2.tgz";
        sha1 = "f916f6d10d45dc171b1be2e6e673fb6e0cc35d0a";
      };
    };
    "base64-js-1.2.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.2.0.tgz";
        sha1 = "a39992d723584811982be5e290bb6a53d86700f1";
      };
    };
    "ieee754-1.1.8" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz";
        sha1 = "be33d40ac10ef1926701f6f08a2d86fbfd1ad3e4";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "lodash-3.5.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.5.0.tgz";
        sha1 = "19bb3f4d51278f0b8c818ed145c74ecf9fe40e6d";
      };
    };
    "debug-2.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.3.3.tgz";
        sha1 = "40c453e67e6e13c901ddec317af8986cda9eff8c";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "vary-1.1.0" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.0.tgz";
        sha1 = "e1e5affbbd16ae768dd2674394b9ad3022653140";
      };
    };
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "content-disposition-0.5.1" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.1.tgz";
        sha1 = "87476c6a67c8daa87e32e87616df883ba7fb071b";
      };
    };
    "content-type-1.0.2" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.2.tgz";
        sha1 = "b7d113aee7a8dd27bd21133c4dc2529df1721eed";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "depd-1.1.0" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.0.tgz";
        sha1 = "e1bd82c6aab6ced965b97b88b17ed3e528ca18c3";
      };
    };
    "encodeurl-1.0.1" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz";
        sha1 = "79e3d58655346909fe6f0f45a5de68103b294d20";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.7.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.7.0.tgz";
        sha1 = "03d30b5f67dd6e632d2945d30d6652731a34d5d8";
      };
    };
    "finalhandler-0.5.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.5.0.tgz";
        sha1 = "e9508abece9b6dba871a6942a1d7911b91911ac7";
      };
    };
    "fresh-0.3.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz";
        sha1 = "651f838e22424e7566de161d8358caa199f83d4f";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "parseurl-1.3.1" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz";
        sha1 = "c8ab8c9223ba34888aa64a297b28853bec18da56";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-1.1.2" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.2.tgz";
        sha1 = "b4cc5f22610d9535824c123aef9d3cf73c40ba37";
      };
    };
    "qs-6.2.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.0.tgz";
        sha1 = "3b7848c03c2dece69a9522b0fae8c4126d745f3b";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "send-0.14.1" = {
      name = "send";
      packageName = "send";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.14.1.tgz";
        sha1 = "a954984325392f51532a7760760e459598c89f7a";
      };
    };
    "serve-static-1.11.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.11.1.tgz";
        sha1 = "d6cce7693505f733c759de57befc1af76c0f0805";
      };
    };
    "type-is-1.6.14" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.14.tgz";
        sha1 = "e219639c17ded1ca0789092dd54a03826b817cb2";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "mime-types-2.1.13" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.13.tgz";
        sha1 = "e07aaa9c6c6b9a7ca3012c69003ad25a39e92a88";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "mime-db-1.25.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.25.0.tgz";
        sha1 = "c18dbd7c73a5dbf6f44a024dc0d165a1e7b1c392";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "forwarded-0.1.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz";
        sha1 = "19ef9874c4ae1c297bcf078fde63a09b66a84363";
      };
    };
    "ipaddr.js-1.1.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.1.1.tgz";
        sha1 = "c791d95f52b29c1247d5df80ada39b8a73647230";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "http-errors-1.5.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.5.1.tgz";
        sha1 = "788c0d2c1de2c81b9e6e8c01843b6b97eb920750";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "setprototypeof-1.0.2" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.2.tgz";
        sha1 = "81a552141ec104b88e89ce383103ad5c66564d08";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "crc-3.4.1" = {
      name = "crc";
      packageName = "crc";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.4.1.tgz";
        sha1 = "65d5830b1a2569557cfb324c0e679998521473ee";
      };
    };
    "on-headers-1.0.1" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.1.tgz";
        sha1 = "928f5d0f470d49342651ea6794b0857c100693f7";
      };
    };
    "uid-safe-2.1.3" = {
      name = "uid-safe";
      packageName = "uid-safe";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-safe/-/uid-safe-2.1.3.tgz";
        sha1 = "077e264a00b3187936b270bb7376a26473631071";
      };
    };
    "base64-url-1.3.3" = {
      name = "base64-url";
      packageName = "base64-url";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-url/-/base64-url-1.3.3.tgz";
        sha1 = "f8b6c537f09a4fc58c99cb86e0b0e9c61461a20f";
      };
    };
    "random-bytes-1.0.0" = {
      name = "random-bytes";
      packageName = "random-bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-bytes/-/random-bytes-1.0.0.tgz";
        sha1 = "4f68a1dc0ae58bd3fb95848c30324db75d64360b";
      };
    };
    "append-field-0.1.0" = {
      name = "append-field";
      packageName = "append-field";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/append-field/-/append-field-0.1.0.tgz";
        sha1 = "6ddc58fa083c7bc545d3c5995b2830cc2366d44a";
      };
    };
    "busboy-0.2.13" = {
      name = "busboy";
      packageName = "busboy";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/busboy/-/busboy-0.2.13.tgz";
        sha1 = "90fc4f6a3967d815616fc976bfa8e56aed0c58b6";
      };
    };
    "concat-stream-1.5.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.2.tgz";
        sha1 = "708978624d856af41a5a741defdd261da752c266";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "object-assign-3.0.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-3.0.0.tgz";
        sha1 = "9bedd5ca0897949bca47e7ff408062d549f587f2";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "dicer-0.2.5" = {
      name = "dicer";
      packageName = "dicer";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/dicer/-/dicer-0.2.5.tgz";
        sha1 = "5996c086bb33218c812c090bddc09cd12facb70f";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "streamsearch-0.1.2" = {
      name = "streamsearch";
      packageName = "streamsearch";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsearch/-/streamsearch-0.1.2.tgz";
        sha1 = "808b9d0e56fc273d809ba57338e929919a1a9f1a";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "buffer-writer-1.0.1" = {
      name = "buffer-writer";
      packageName = "buffer-writer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-writer/-/buffer-writer-1.0.1.tgz";
        sha1 = "22a936901e3029afcd7547eb4487ceb697a3bf08";
      };
    };
    "packet-reader-0.2.0" = {
      name = "packet-reader";
      packageName = "packet-reader";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/packet-reader/-/packet-reader-0.2.0.tgz";
        sha1 = "819df4d010b82d5ea5671f8a1a3acf039bcd7700";
      };
    };
    "pg-connection-string-0.1.3" = {
      name = "pg-connection-string";
      packageName = "pg-connection-string";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-connection-string/-/pg-connection-string-0.1.3.tgz";
        sha1 = "da1847b20940e42ee1492beaf65d49d91b245df7";
      };
    };
    "pg-pool-1.6.0" = {
      name = "pg-pool";
      packageName = "pg-pool";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-pool/-/pg-pool-1.6.0.tgz";
        sha1 = "2e300199927b6d7db6be71e2e3435dddddf07b41";
      };
    };
    "pg-types-1.11.0" = {
      name = "pg-types";
      packageName = "pg-types";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-types/-/pg-types-1.11.0.tgz";
        sha1 = "aae91a82d952b633bb88d006350a166daaf6ea90";
      };
    };
    "pgpass-1.0.1" = {
      name = "pgpass";
      packageName = "pgpass";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pgpass/-/pgpass-1.0.1.tgz";
        sha1 = "0de8b5bef993295d90a7e17d976f568dcd25d49f";
      };
    };
    "semver-4.3.2" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.2.tgz";
        sha1 = "c7a07158a80bedd052355b770d82d6640f803be7";
      };
    };
    "generic-pool-2.4.2" = {
      name = "generic-pool";
      packageName = "generic-pool";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-pool/-/generic-pool-2.4.2.tgz";
        sha1 = "886bc5bf0beb7db96e81bcbba078818de5a62683";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "ap-0.2.0" = {
      name = "ap";
      packageName = "ap";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ap/-/ap-0.2.0.tgz";
        sha1 = "ae0942600b29912f0d2b14ec60c45e8f330b6110";
      };
    };
    "postgres-array-1.0.0" = {
      name = "postgres-array";
      packageName = "postgres-array";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-array/-/postgres-array-1.0.0.tgz";
        sha1 = "48c2e82935b178bf805e0dff689d137eec2bfe6b";
      };
    };
    "postgres-bytea-1.0.0" = {
      name = "postgres-bytea";
      packageName = "postgres-bytea";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz";
        sha1 = "027b533c0aa890e26d172d47cf9ccecc521acd35";
      };
    };
    "postgres-date-1.0.3" = {
      name = "postgres-date";
      packageName = "postgres-date";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.3.tgz";
        sha1 = "e2d89702efdb258ff9d9cee0fe91bd06975257a8";
      };
    };
    "postgres-interval-1.0.2" = {
      name = "postgres-interval";
      packageName = "postgres-interval";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.0.2.tgz";
        sha1 = "7261438d862b412921c6fdb7617668424b73a6ed";
      };
    };
    "split-1.0.0" = {
      name = "split";
      packageName = "split";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.0.tgz";
        sha1 = "c4395ce683abcd254bc28fe1dabb6e5c27dcffae";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "array-uniq-1.0.2" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.2.tgz";
        sha1 = "5fcc373920775723cfd64d65c64bef53bf9eba6d";
      };
    };
    "double-ended-queue-2.1.0-0" = {
      name = "double-ended-queue";
      packageName = "double-ended-queue";
      version = "2.1.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz";
        sha1 = "103d3527fd31528f40188130c841efdd78264e5c";
      };
    };
    "redis-commands-1.3.0" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.3.0.tgz";
        sha1 = "4307d8094aee1315829ab6729b37b99f62365d63";
      };
    };
    "redis-parser-2.3.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-2.3.0.tgz";
        sha1 = "313a47965e49ee35ab3a86c93388b403d76237f6";
      };
    };
    "s3-download-stream-0.0.5" = {
      name = "s3-download-stream";
      packageName = "s3-download-stream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/s3-download-stream/-/s3-download-stream-0.0.5.tgz";
        sha1 = "2ac581a8926adbf5e51861a788acf15e5d1797ec";
      };
    };
    "through2-0.6.5" = {
      name = "through2";
      packageName = "through2";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-0.6.5.tgz";
        sha1 = "41ab9c67b29d57209071410e1d7a7a968cd3ad48";
      };
    };
    "SimpleQueue-0.0.1" = {
      name = "SimpleQueue";
      packageName = "SimpleQueue";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/SimpleQueue/-/SimpleQueue-0.0.1.tgz";
        sha1 = "74466490afa37c1878653767f23c59067a8e7d70";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "async.ensureasync-0.5.2" = {
      name = "async.ensureasync";
      packageName = "async.ensureasync";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.ensureasync/-/async.ensureasync-0.5.2.tgz";
        sha1 = "c3c7e4a4e9b31d96875d56b8504598446e1e305d";
      };
    };
    "async.queue-0.5.2" = {
      name = "async.queue";
      packageName = "async.queue";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.queue/-/async.queue-0.5.2.tgz";
        sha1 = "8d5d90812e1481066bc0904e8cc1712b17c3bd7c";
      };
    };
    "bottleneck-1.15.0" = {
      name = "bottleneck";
      packageName = "bottleneck";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bottleneck/-/bottleneck-1.15.0.tgz";
        sha1 = "a636f59bc2783d87d5ac7f30ff30a22e440ffbc1";
      };
    };
    "lodash.chunk-4.2.0" = {
      name = "lodash.chunk";
      packageName = "lodash.chunk";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.chunk/-/lodash.chunk-4.2.0.tgz";
        sha1 = "66e5ce1f76ed27b4303d8c6512e8d1216e8106bc";
      };
    };
    "sendgrid-rest-2.3.0" = {
      name = "sendgrid-rest";
      packageName = "sendgrid-rest";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sendgrid-rest/-/sendgrid-rest-2.3.0.tgz";
        sha1 = "662ef95a93c73c3e0a4e7a61e3880a10c78dd24a";
      };
    };
    "async.util.ensureasync-0.5.2" = {
      name = "async.util.ensureasync";
      packageName = "async.util.ensureasync";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.ensureasync/-/async.util.ensureasync-0.5.2.tgz";
        sha1 = "10907f2cbd067a061f99ae6d22e08ced30db0d68";
      };
    };
    "async.util.restparam-0.5.2" = {
      name = "async.util.restparam";
      packageName = "async.util.restparam";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.restparam/-/async.util.restparam-0.5.2.tgz";
        sha1 = "03efebf3c0277b97220e525aba750f5e04fc80cd";
      };
    };
    "async.util.setimmediate-0.5.2" = {
      name = "async.util.setimmediate";
      packageName = "async.util.setimmediate";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.setimmediate/-/async.util.setimmediate-0.5.2.tgz";
        sha1 = "2812ebabf2a58027758d4bc7793d1ccfaf10255f";
      };
    };
    "async.util.queue-0.5.2" = {
      name = "async.util.queue";
      packageName = "async.util.queue";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.queue/-/async.util.queue-0.5.2.tgz";
        sha1 = "57f65abe1a3cdf273d31abd28ab95425f8222ee5";
      };
    };
    "async.util.arrayeach-0.5.2" = {
      name = "async.util.arrayeach";
      packageName = "async.util.arrayeach";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.arrayeach/-/async.util.arrayeach-0.5.2.tgz";
        sha1 = "58c4e98028d55d69bfb05aeb3af44e0a555a829c";
      };
    };
    "async.util.isarray-0.5.2" = {
      name = "async.util.isarray";
      packageName = "async.util.isarray";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.isarray/-/async.util.isarray-0.5.2.tgz";
        sha1 = "e62dac8f2636f65875dcf7521c2d24d0dfb2bbdf";
      };
    };
    "async.util.map-0.5.2" = {
      name = "async.util.map";
      packageName = "async.util.map";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.map/-/async.util.map-0.5.2.tgz";
        sha1 = "e588ef86e0b3ab5f027d97af4d6835d055ca69d6";
      };
    };
    "async.util.noop-0.5.2" = {
      name = "async.util.noop";
      packageName = "async.util.noop";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.noop/-/async.util.noop-0.5.2.tgz";
        sha1 = "bdd62b97cb0aa3f60b586ad148468698975e58b9";
      };
    };
    "async.util.onlyonce-0.5.2" = {
      name = "async.util.onlyonce";
      packageName = "async.util.onlyonce";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async.util.onlyonce/-/async.util.onlyonce-0.5.2.tgz";
        sha1 = "b8e6fc004adc923164d79e32f2813ee465c24ff2";
      };
    };
  };
  args = {
    name = "trivecta";
    packageName = "trivecta";
    version = "1.0.0";
    inherit src;
    dependencies = [
      (sources."async-2.1.4" // {
        dependencies = [
          sources."lodash-4.17.2"
        ];
      })
      (sources."aws-sdk-2.7.10" // {
        dependencies = [
          (sources."buffer-4.9.1" // {
            dependencies = [
              sources."base64-js-1.2.0"
              sources."ieee754-1.1.8"
              sources."isarray-1.0.0"
            ];
          })
          sources."crypto-browserify-1.0.9"
          sources."jmespath-0.15.0"
          sources."querystring-0.2.0"
          sources."sax-1.1.5"
          (sources."url-0.10.3" // {
            dependencies = [
              sources."punycode-1.3.2"
            ];
          })
          sources."uuid-3.0.0"
          sources."xml2js-0.4.15"
          (sources."xmlbuilder-2.6.2" // {
            dependencies = [
              sources."lodash-3.5.0"
            ];
          })
        ];
      })
      sources."bcryptjs-2.3.0"
      (sources."connect-redis-3.1.0" // {
        dependencies = [
          (sources."debug-2.3.3" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
        ];
      })
      (sources."cors-2.8.1" // {
        dependencies = [
          sources."vary-1.1.0"
        ];
      })
      sources."dot-lens-1.2.3"
      (sources."express-4.14.0" // {
        dependencies = [
          (sources."accepts-1.3.3" // {
            dependencies = [
              (sources."mime-types-2.1.13" // {
                dependencies = [
                  sources."mime-db-1.25.0"
                ];
              })
              sources."negotiator-0.6.1"
            ];
          })
          sources."array-flatten-1.1.1"
          sources."content-disposition-0.5.1"
          sources."content-type-1.0.2"
          sources."cookie-0.3.1"
          sources."cookie-signature-1.0.6"
          (sources."debug-2.2.0" // {
            dependencies = [
              sources."ms-0.7.1"
            ];
          })
          sources."depd-1.1.0"
          sources."encodeurl-1.0.1"
          sources."escape-html-1.0.3"
          sources."etag-1.7.0"
          (sources."finalhandler-0.5.0" // {
            dependencies = [
              sources."statuses-1.3.1"
              sources."unpipe-1.0.0"
            ];
          })
          sources."fresh-0.3.0"
          sources."merge-descriptors-1.0.1"
          sources."methods-1.1.2"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          sources."parseurl-1.3.1"
          sources."path-to-regexp-0.1.7"
          (sources."proxy-addr-1.1.2" // {
            dependencies = [
              sources."forwarded-0.1.0"
              sources."ipaddr.js-1.1.1"
            ];
          })
          sources."qs-6.2.0"
          sources."range-parser-1.2.0"
          (sources."send-0.14.1" // {
            dependencies = [
              sources."destroy-1.0.4"
              (sources."http-errors-1.5.1" // {
                dependencies = [
                  sources."inherits-2.0.3"
                  sources."setprototypeof-1.0.2"
                ];
              })
              sources."mime-1.3.4"
              sources."ms-0.7.1"
              sources."statuses-1.3.1"
            ];
          })
          sources."serve-static-1.11.1"
          (sources."type-is-1.6.14" // {
            dependencies = [
              sources."media-typer-0.3.0"
              (sources."mime-types-2.1.13" // {
                dependencies = [
                  sources."mime-db-1.25.0"
                ];
              })
            ];
          })
          sources."utils-merge-1.0.0"
          sources."vary-1.1.0"
        ];
      })
      (sources."express-session-1.14.2" // {
        dependencies = [
          sources."cookie-0.3.1"
          sources."cookie-signature-1.0.6"
          sources."crc-3.4.1"
          (sources."debug-2.2.0" // {
            dependencies = [
              sources."ms-0.7.1"
            ];
          })
          sources."depd-1.1.0"
          sources."on-headers-1.0.1"
          sources."parseurl-1.3.1"
          (sources."uid-safe-2.1.3" // {
            dependencies = [
              sources."base64-url-1.3.3"
              sources."random-bytes-1.0.0"
            ];
          })
          sources."utils-merge-1.0.0"
        ];
      })
      (sources."multer-1.2.0" // {
        dependencies = [
          sources."append-field-0.1.0"
          (sources."busboy-0.2.13" // {
            dependencies = [
              (sources."dicer-0.2.5" // {
                dependencies = [
                  sources."streamsearch-0.1.2"
                ];
              })
              (sources."readable-stream-1.1.14" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."isarray-0.0.1"
                  sources."string_decoder-0.10.31"
                  sources."inherits-2.0.3"
                ];
              })
            ];
          })
          (sources."concat-stream-1.5.2" // {
            dependencies = [
              sources."inherits-2.0.3"
              sources."typedarray-0.0.6"
              (sources."readable-stream-2.0.6" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."string_decoder-0.10.31"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          (sources."mkdirp-0.5.1" // {
            dependencies = [
              sources."minimist-0.0.8"
            ];
          })
          sources."object-assign-3.0.0"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          (sources."type-is-1.6.14" // {
            dependencies = [
              sources."media-typer-0.3.0"
              (sources."mime-types-2.1.13" // {
                dependencies = [
                  sources."mime-db-1.25.0"
                ];
              })
            ];
          })
          sources."xtend-4.0.1"
        ];
      })
      (sources."pg-6.1.0" // {
        dependencies = [
          sources."buffer-writer-1.0.1"
          sources."packet-reader-0.2.0"
          sources."pg-connection-string-0.1.3"
          (sources."pg-pool-1.6.0" // {
            dependencies = [
              sources."generic-pool-2.4.2"
              sources."object-assign-4.1.0"
            ];
          })
          (sources."pg-types-1.11.0" // {
            dependencies = [
              sources."ap-0.2.0"
              sources."postgres-array-1.0.0"
              sources."postgres-bytea-1.0.0"
              sources."postgres-date-1.0.3"
              (sources."postgres-interval-1.0.2" // {
                dependencies = [
                  sources."xtend-4.0.1"
                ];
              })
            ];
          })
          (sources."pgpass-1.0.1" // {
            dependencies = [
              (sources."split-1.0.0" // {
                dependencies = [
                  sources."through-2.3.8"
                ];
              })
            ];
          })
          sources."semver-4.3.2"
        ];
      })
      (sources."randomstring-1.1.5" // {
        dependencies = [
          sources."array-uniq-1.0.2"
        ];
      })
      (sources."redis-2.6.3" // {
        dependencies = [
          sources."double-ended-queue-2.1.0-0"
          sources."redis-commands-1.3.0"
          sources."redis-parser-2.3.0"
        ];
      })
      (sources."s3-blob-store-1.2.3" // {
        dependencies = [
          (sources."debug-2.3.3" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          (sources."mime-types-2.1.13" // {
            dependencies = [
              sources."mime-db-1.25.0"
            ];
          })
          (sources."s3-download-stream-0.0.5" // {
            dependencies = [
              sources."SimpleQueue-0.0.1"
              sources."clone-1.0.2"
            ];
          })
          (sources."through2-0.6.5" // {
            dependencies = [
              (sources."readable-stream-1.0.34" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."isarray-0.0.1"
                  sources."string_decoder-0.10.31"
                  sources."inherits-2.0.3"
                ];
              })
              sources."xtend-4.0.1"
            ];
          })
        ];
      })
      (sources."sendgrid-4.7.1" // {
        dependencies = [
          (sources."async.ensureasync-0.5.2" // {
            dependencies = [
              (sources."async.util.ensureasync-0.5.2" // {
                dependencies = [
                  sources."async.util.restparam-0.5.2"
                  sources."async.util.setimmediate-0.5.2"
                ];
              })
            ];
          })
          (sources."async.queue-0.5.2" // {
            dependencies = [
              (sources."async.util.queue-0.5.2" // {
                dependencies = [
                  sources."async.util.arrayeach-0.5.2"
                  sources."async.util.isarray-0.5.2"
                  sources."async.util.map-0.5.2"
                  sources."async.util.noop-0.5.2"
                  sources."async.util.onlyonce-0.5.2"
                  sources."async.util.setimmediate-0.5.2"
                ];
              })
            ];
          })
          sources."bottleneck-1.15.0"
          (sources."debug-2.3.3" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."lodash.chunk-4.2.0"
          sources."sendgrid-rest-2.3.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
